version: '3.5'

services:

  userDB:
    image: mongo
    restart: always
    container_name: userDatabase
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./.docker/data/db:/data/db
      - ./.docker/mongo-init.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - mongo_db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  serverCache:
    image: redis:latest
    restart: always
    volumes: 
      - ./.docker/data/cache:/data/cache
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment: 
      - REDIS_REPLICATION_MODE=master

networks:
  mongo_db:

volumes:
  data:
