name: 'Build Testing'

on:
  workflow_dispatch:
  push:
    branches:
      - 'feat/**'
    paths:
      - 'src/**.ts'
      - 'src/**/**.ts'
  pull_request:
  
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm prebuild; pnpm build
